=== josezitopedrito/PRI/PRI-Teste/PR/pr_final.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT pr (meta,workTeam,abstract,deliverables) >

<!ELEMENT meta (keyName,title,subtitle?,bDate,eDate,supervisor) >

<!ELEMENT keyName (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT bDate (#PCDATA) >
<!ELEMENT eDate (#PCDATA) >
<!ELEMENT supervisor (name,email?,homepage?) >

<!ELEMENT name (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ELEMENT homepage (#PCDATA) >

<!ELEMENT workTeam (member+) >

<!ELEMENT member (identifier,name,email,photo?) >

<!ELEMENT identifier (#PCDATA) >
<!ELEMENT photo EMPTY >
<!ATTLIST photo
            path CDATA #REQUIRED >

<!ELEMENT abstract (p+) >

<!ELEMENT p (#PCDATA|b|i|u|xref)* >

<!ELEMENT b (#PCDATA|i|u|xref)* >
<!ELEMENT i (#PCDATA|b|u|xref)* >
<!ELEMENT u (#PCDATA|b|i|xref)* >
<!ELEMENT xref (#PCDATA) >

<!ELEMENT deliverables (deliverable+) >

<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable
            path CDATA #REQUIRED>

=== josezitopedrito/PRI/PRI-7ºTPC/PR/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr_final.dtd">
<pr>
    <meta>
        <keyName>PRI2019-A80424-T7</keyName>
        <title>Servidor com informação acerca de obras musicais e dos respetivos compositores </title>
        <bDate>11 de novembro de 2019</bDate>
        <eDate>18 de novembro de 2019</eDate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <email>jcr@di.uminho.pt</email>
            <homepage>http://www4.di.uminho.pt/~jcr/</homepage>
        </supervisor>
    </meta>
    <workTeam>
        <member>
            <identifier>A80424</identifier>
            <name>José Pedro Saraiva de Carvalho</name>
            <email>a80424@alunos.uminho.pt</email>
            <photo path="photo.jpg"/>
        </member>
    </workTeam>
    <abstract>
        
        <p>Este trabalho semanal consistia em desenvolver um servidor que disponibiliza as informações acerca de um conjunto de obras e respetivos compositores armazenados numa base de dados não relacional em <i>MongoDB</i>, com o auxílio de <i>NodeJS</i> e de <i>ExpressJS</i>.</p>
        <p>O servidor é capaz de receber pedidos de <b>GET</b> para o conjunto total de obras, para a informação individual de cada obra, para a informação acerca do período, ano de criação e compositor da obra, para o conjunto total de compositores e para as obras de cada compositor.</p>
        
    </abstract>
    <deliverables>
        <deliverable path="../obras">Diretoria que contém o TPC7</deliverable>
        <deliverable path="pr.xml">Ficheiro XML que contém a informação deste PR</deliverable>
        <deliverable path="pr.xsl">Stylesheet que contém a informação deste PR</deliverable>
        <deliverable path="../obras.json">Ficheiro em JSON que contem a informação que depois é apropriada pela base de dados em mongo.</deliverable>
    </deliverables>
</pr>

=== josezitopedrito/PRI/PRI-5ºTPC/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../pr_final.dtd">
<pr>
    <meta>
        <keyName>PRI2019-A80424-T5</keyName>
        <title>Servidor de gestão de informações acerca de alunos em NodeJS e utilizando ExpressJS </title>
        <bDate>28 de outubro de 2019</bDate>
        <eDate>4 de novembro de 2019</eDate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <email>jcr@di.uminho.pt</email>
            <homepage>http://www4.di.uminho.pt/~jcr/</homepage>
        </supervisor>
    </meta>
    <workTeam>
        <member>
            <identifier>A80424</identifier>
            <name>José Pedro Saraiva de Carvalho</name>
            <email>a80424@alunos.uminho.pt</email>
            <photo path="photo.jpg"/>
        </member>
    </workTeam>
    <abstract>
        
        <p>Este trabalho semanal consistia em desenvolver um servidor que disponibiliza as informações acerca de um conjunto de alunos com o auxílio de <i>NodeJS</i> e de <i>ExpressJS</i>.</p>
        <p>O servidor é capaz de receber pedidos de <b>GET</b> para o conjunto total de alunos e para a informação individual de cada um destes. O servidor também é capaz de receber pedidos de <b>POST</b> para acrescentar alunos e novas botas a alunos já existentes. Por fim o servidor é capaz de receber pedidos de <b>DELETE</b> para apagar, quer alunos, quer algumas notas de alunos.</p>
        <p>A informação pertencente aos alunos está contida no ficheiro <i>alunos.json</i> na diretoria <i>data</i>.</p>
        
    </abstract>
    <deliverables>
        <deliverable path="galunos">Diretoria que contém a o TPC5</deliverable>
        <deliverable path="pr.xml">Ficheiro XML que contém a informação deste PR</deliverable>
        <deliverable path="pr.xsl">Stylesheet que contém a informação deste PR</deliverable>
    </deliverables>
</pr>

=== josezitopedrito/PRI/PRI-6ºTPC/PR/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr_final.dtd">
<pr>
    <meta>
        <keyName>PRI2019-A80424-T6</keyName>
        <title>Servidor utilizando NodeJS e ExpressJS com dados obtidos de uma BD em MongoDB </title>
        <bDate>4 de novembro de 2019</bDate>
        <eDate>11 de novembro de 2019</eDate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <email>jcr@di.uminho.pt</email>
            <homepage>http://www4.di.uminho.pt/~jcr/</homepage>
        </supervisor>
    </meta>
    <workTeam>
        <member>
            <identifier>A80424</identifier>
            <name>José Pedro Saraiva de Carvalho</name>
            <email>a80424@alunos.uminho.pt</email>
            <photo path="photo.jpg"/>
        </member>
    </workTeam>
    <abstract>
        
        <p>Este trabalho semanal consistia em desenvolver um servidor que disponibiliza as informações acerca de um conjunto de filmes armazenados numa base de dados não relacional em <i>MongoDB</i>, com o auxílio de <i>NodeJS</i> e de <i>ExpressJS</i>.</p>
        <p>O servidor é capaz de receber pedidos de <b>GET</b> para o conjunto total de filmes e para a informação individual de cada filme. O servidor também é capaz de receber pedidos de <b>POST</b> para acrescentar filmes. Por fim o servidor é capaz de receber pedidos de <b>DELETE</b> para apagar filmes.</p>
        
    </abstract>
    <deliverables>
        <deliverable path="../gfilmes">Diretoria que contém a o TPC5</deliverable>
        <deliverable path="pr.xml">Ficheiro XML que contém a informação deste PR</deliverable>
        <deliverable path="pr.xsl">Stylesheet que contém a informação deste PR</deliverable>
    </deliverables>
</pr>

=== josezitopedrito/PRI/PRI-Teste/PR/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "pr_final.dtd">
<pr>
    <meta>
        <keyName>PRI2020-Teste</keyName>
        <title>Teste de Avaliação </title>
        <bDate>13 de janeiro de 2020</bDate>
        <eDate>13 de janeiro de 2020</eDate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <email>jcr@di.uminho.pt</email>
            <homepage>http://www4.di.uminho.pt/~jcr/</homepage>
        </supervisor>
    </meta>
    <workTeam>
        <member>
            <identifier>A80424</identifier>
            <name>José Pedro Saraiva de Carvalho</name>
            <email>a80424@alunos.uminho.pt</email>
            <photo path="photo.jpg"/>
        </member>
    </workTeam>
    <abstract>
        <p>No primeiro exercício foi utilizado o MongoDB para persistência de dados. Primeiro foi corrigido o dataset em JSON com a ajuda do JSON Formater <xref>https://jsonformatter.curiousconcept.com/</xref>.Após isto o ficheiro JSON resultante foi importado para o Mongo com o seguinte comando <i>mongoimport -d pubs -c pubs --jsonArray jcrpubs.json</i>.</p>
        <p>De seguida na diretoria pubs escreva no terminal <i>npm update</i>, <i>npm i mongoose --save</i> (para obter o mongoose), <i>npm i axios --save</i> (para obter o axios) e, por fim, para correr a aplicação escreva <i>npm start</i></p>
        <p>O último get não foi conseguido</p>
        <p>A porta utilizada foi a 3003.</p>
        <p>As respostas à primeira parte no ex dois encontram-se na diretoria Perguntas no ficheiro <i>ex.json</i></p>
        
        <p>Na segunda parte do segundo exercício http://localhost:3004/</p>
        <p>Os dados foram obtidos diretamante da página da CLAV.</p>
        <p>De seguida na diretoria pubs escreva no terminal <i>npm update</i>, <i>npm i mongoose --save</i> (para obter o mongoose), <i>npm i axios --save</i> (para obter o axios) e, por fim, para correr a aplicação escreva <i>npm start</i></p>
        <p>A porta utilizada foi a 3004.</p>
        <p>Neste exercício foram feitas apenas as alíneas 1,3(os pugs entidades, dono e participante nao se encontram corretos) e 4</p>
    </abstract>
    <deliverables>
        <deliverable path="pr.xml">Ficheiro XML que contém a informação deste PR</deliverable>
        <deliverable path="pr.xsl">Stylesheet que contém a informação deste PR</deliverable>
        <deliverable path="../Ex1">Diretoria com o primeiro exercício do teste</deliverable>
        <deliverable path="../Ex2">Diretoria com o segundo exercício do teste</deliverable>
    </deliverables>
</pr>

=== josezitopedrito/PRI/PRI-4ºTPC/pr.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pr SYSTEM "../pr_final.dtd">
<pr>
    <meta>
        <keyName>PRI2019-A80424-T4</keyName>
        <title>Stylesheet para a elaboração do servidor em nodejs acerca do arquivo sonoro</title>
        <bDate>21 de outubro de 2019</bDate>
        <eDate>28 de outubro de 2019</eDate>
        <supervisor>
            <name>José Carlos Ramalho</name>
            <email>jcr@di.uminho.pt</email>
            <homepage>http://www4.di.uminho.pt/~jcr/</homepage>
        </supervisor>
    </meta>
    <workTeam>
        <member>
            <identifier>A80424</identifier>
            <name>José Pedro Saraiva de Carvalho</name>
            <email>a80424@alunos.uminho.pt</email>
            <photo path="photo.jpg"/>
        </member>
    </workTeam>
    <abstract>
        <p>Na mesma diretoria deste manifesto estão mais 6 ficheiros e 1 diretoria.</p>
        <p>Nos ficheiros pr.xml e pr.xsl encontra-se a informação necessária para elaborar esta página em HTML. </p>
        <p>No ficheiro w3.css encontra-se codigo css para ser implementado nas páginas de individuais de cada música.</p>
        <p>O ficheiro datasetGen.xsl contém a stylesheet que criou as páginas em XML para cada música.</p>
        <p>O ficheiro doc2html.xsl contém a stylesheet necessária para passar cada ficheiro individual xml para um ficheiro individual html.</p>
        <p>O ficheiro arq-son-EVO.xml é o ficheiro em XML que conté informação de todas as músicas do arquivo sonoro.</p>
        <p>A diretoria data contém todos os ficheiros em XML individuais de todas as músicas no arquivo sonoro.</p>
        <p>O ficheiro arq.js contém o script necessário para criar o servidor.</p>
        
        <p>Este trabalho semanal consistia em desenvolver um servidor com nodeJS que disponibiliza as informações acerca das músicas com o auxílio do <i>nodeJS</i>.</p>
        
    </abstract>
    <deliverables>
        <deliverable path="pr.xml">Ficheiro XML do manifesto.</deliverable>
        <deliverable path="pr.xsl">Stylesheet relativa à elaboração do HTML do manifesto.</deliverable>
        <deliverable path="datasetGen.xsl">Stylesheet que elabora os ficheiros individuais em XML a partir do arquivo sonoro.</deliverable>
        <deliverable path="doc2html.xsl">Stylesheet que elabora o HTML a partir dos ficheiros individuais XML.</deliverable>
        <deliverable path="arq-som-EVO.xml">Ficheiro XML que apresenta as caraterísticas do arquivo sonoro.</deliverable>
        <deliverable path="data">Diretoria com os ficheiros individuais XML.</deliverable>
        <deliverable path="w3.css">CSS dos ficheiros individuais de XML</deliverable>
    </deliverables>
</pr>
